### ISSUE TITLE
工具栏目排版有些问题

### ISSUE THREAD

**Issue by anwzx** [hw798/hw798#2]
## **我测试了三个浏览器结果都是一样的**

![360极速.png](https://i.loli.net/2018/01/08/5a53169393c1b.png)

![charom.png](https://i.loli.net/2018/01/08/5a531693a02a1.png)

![huohu.png](https://i.loli.net/2018/01/08/5a531693a144b.png)

**Comment by hw798** [comment]
O(∩_∩)O谢谢这么用心反馈，已解决，目前把Chrome单拿出来了，方便以后推荐些其他相关资源，例如扩展开发
